# login-shell=no


font=Roboto Mono Nerd Font Mono:size=8
dpi-aware=no

# initial-window-size-pixels=700x500 # Or,
initial-window-size-chars=100x22
# initial-window-mode=windowed
pad=5x5
# resize-delay-ms=100
resize-by-cells=no

[environment]

[bell]

[scrollback]

[url]

[mouse]


[colors]
alpha=1.0

[csd]
preferred=server


